@extends('layouts.app')
@section('content')
	
<section class="static-pages">
	<div class="container">
		<div class="row">
			<div class="col-md-12 col-sm-12">
				<div class="terms_conditions">	
				<h2>Terms and Conditions</h2>				
				<div class="contentTitle">
					<h4>Acknowledgment and acceptance of Terms and Conditions</h4></div>
					<ul>
						<li>Futuristic (The Site) is owned and operated by Futuristic Skills and Capabilities (we, us).</li><br>
						<li>The Site refers to any and all access to Futuristic resources, via static or mobile devices, in either website or application format. Your access to and use of the Site (collectively, your Access) is conditional on your acceptance and compliance with the terms, conditions, notices and disclaimers contained or referred to on this page (Terms and Conditions). Your Access to the Site constitutes your agreement to be bound by the Terms and Conditions and that agreement may be enforced by us. If you do not agree with any of these Terms and Conditions, you must cease using the Site.</li><br>
						<li>These Terms and Conditions apply to all users, regardless of whether a licence to Access the Site has been purchased by a school / educational institution on behalf of students and teachers, or directly by a student or parent. In the case of students who are minors, permission must be sought by that student’s school or parent / guardian (as applicable) before that student is provided with Access to the Site.</li><br>
						<li>We reserve the right, at our discretion, to revise, amend and update the Terms and Conditions at any time effective on the date of posting to the Site of the new and amended provisions.</li><br>
					</ul>   
					<div class="contentTitle">
					<h4>Privacy</h4></div>
					<ul>
						<li>By agreeing to these Terms and Conditions, you agree to the terms of our Privacy Policy. Before using the Site, please carefully review our Privacy Policy. All personal information provided to us as a result of your Access will be handled in accordance with ourPrivacy Policy, and by Accessing the Site, or allowing your child/student to Access the Site, you consent to the collection, storage, use and dissemination of your personal information in accordance with this Privacy Policy.</li><br>
					</ul>
					<div class="contentTitle"><h4>Ownership of content</h4></div>
					<ul>
						<li>The Site, including without limitation all materials displayed on or produced through the Site, information, text, illustrations, graphics, video, sound recordings, software including the code comprising or used to operate the Site, tools, results derived from the use of software and tools, data collected from Access to the Site, names, logos and trade marks on the Site (collectively, Content) and the intellectual property therein belong to us and are protected by copyright, trade mark, trade secrets and other intellectual property laws unless expressly indicated otherwise on the Site.</li><br>
						<li>You must not modify, copy, reproduce, republish, frame, reverse engineer, download onto a computer, upload to a third party, post, transmit or distribute this Content in any way except as expressly provided for in these Terms and Conditionsor with our express prior written consent.</li>
						<br>
					</ul>
					<div class="contentTitle"><h4>User code of conduct and Access rights</h4></div>
					<ul>
						<li>Any user, including, students or teachers, found to be in breach of these Terms and Conditions, acting in a manner that we deem to be inappropriate or inconsistent with the spirit of these Terms and Conditions(e.g. submitting fraudulent results), or that is unlawful or prohibited by any laws applicable to the Site, may have their Access to the Site revoked.</li></br>
						<li>You must not access or use the Site or the Content in any manner or for any purpose which is illegal or prohibited by any laws that apply to you, violates our rights in any way, or is prohibited by the Terms and Conditions.</li></br>
						<li>Users of the Site must protect their usernames and passwords from unauthorised use. If you suspect any unauthorised use of your account, please notify us immediately.</li></br>
						<li>You may view the Site using your web browser and save an electronic copy, or print out a copy, of parts of this Site solely for your own personal use, information, research or study, but only if you keep all Content intact and in the same form as presented on the Site (including without limitation all copyright, trade mark and other proprietary notices and all advertisements). In the case of school/educational institution customers, you may use the information generated by features of the Site, such as student reports, for non-commercial educational purposes.</li></br>
						<li>You must not use the Content for commercial purposes without first obtaining our express written authority.</li><br>
						<li>You must take your own precautions to ensure that the process, which you employ for accessing the Site, does not expose you to the risk of viruses, malicious computer code or other forms of interference, which may damage your own computer system. We do not accept responsibility for any interference or damage to your own computer system or data, which arises in connection with your Access.</li><br>
						<li>The Site and our Content is continuously evolving. We reserve the right to delete, modify, change, evolve and improve existing Content, including curriculum, product features and tools, at any time without notice or consent.</li><br>
						<li>A paid subscription to any Futuristic resource permits the subscribed user access to the resource in its native format across both static and mobile devices. We reserve the right to levy additional charges for access to resources outside of this limitation. In some cases, additional subscription charges may be levied for non-native access, premium additional content, printed content, mobile device access to standalone components of Futuristic resources as well as special Futuristic educational events or competitions.</li><br>
					</ul>
					<div class="contentTitle"><h4>Individual licences ("Home subscriptions")</h4></div>
					<ul>
						<li>Futuristic individual subscription licences are for individual, non-commercial, purposes and are non-transferable.</li><br>
						<li>Users are responsible for their own internet usage charges. It is the responsibility of the user to ensure their computer and internet access is sufficient to access Futuristic.</li><br>
						<li>Users must agree to the Futuristic Privacy Policy.</li><br>
						<li>Trading & Shipping Policy: Web-delivered goods are supplied immediately upon processing of credit card details. All taxes are detailed on the tax invoice provided to the client. Card types accepted: Visa, MasterCard, Bank cards. We do not accept Amex or Diners Club.</li><br>
						<li>Customer Service Policy: All goods/services supplied will be in good working order. All faulty goods will be exchanged for a working version at no additional cost to the client.</li><br>
						<li>Returns/Refunds Policy: Futuristic offers a no-questions-asked10 day money back guaranteefor individual subscription licences. No refunds will be offered after this time.</li><br>
						<li>Consumer Data Policy: Purchasing information provided from online transactions is used for accounting purposes only. After payment, no credit card details are retained or stored. Stringent physical and technological measures are taken to protect customer information.</li><br>
					</ul>
					<div class="contentTitle"><h4>Disclaimer and limitation of liability</h4></div>
					<ul>
						<li>Although we have no reason to believe that any information contained in this Site is inaccurate, we do not warrant the accuracy, adequacy or completeness of the information.</li><br>
						<li>We do not accept responsibility for loss suffered as a result of your reliance on the accuracy or currency of information contained in this Site. We and our directors, officers, agents, employees and contractors do not guarantee or warrant the Site will be uninterrupted, without delay, error-free, omission-free or free of viruses. The Content is provided “as is” without warranties of any kind, express or implied, including as to accuracy, timeliness and completeness except where warranties are made non-excludable by applicable legislation.</li><br>
						<li>Neither we nor our directors, officers, agents, employees or contractors will be liable for any loss or damage, however arising (whether in negligence or otherwise), in connection with your Access, the Content or any omissions from the Content, except where liability is made non-excludable by applicable legislation.</li><br>
					</ul>
					<div class="contentTitle"><h4>Indemnity</h4></div>
					<ul>
						<li>You agree to indemnify us and our directors, officers, agents, employees and contractors and keep us and all of them indemnified, against all loss, actions, proceedings, costs, expenses (including legal fees), claims and damages arising from any breach by you of the Terms and Conditions, or reliance by you on any information obtained through the Site or your Access to the Site.</li><br>
					</ul>
					<div class="contentTitle"><h4>Copyright</h4></div>
					<ul>
						<li>Copyright in this Site (including text, graphics, logos, icons, sound recordings and software) is owned or licensed by us. Other than for the purposes of, and subject to the conditions prescribed under, the Australian Copyright Act 1968 (Cth) and similar legislation which applies in your location, and except as expressly authorised by these Terms and Conditions, you may not in any form or by any means:<br>
							<ul>
								<li>adapt, reproduce, store, distribute, print, display, perform, publish or create derivative works from any part of this Site; or</li><br>
								<li>commercialise any information, products or services obtained from any part of this Site.</li><br>
							<ul>
						</li>
						<li>Where copyright legislation in a location includes a remunerated scheme to permit educational institutions to copy or print any part of the Site, we will claim for remuneration under that scheme where worksheets are printed or photocopied by teachers for use by students, and where teachers direct students to print or photocopy worksheets for use by students at school. A worksheet is a page of learning, designed for a student to write on using an ink pen or pencil. This may lead to an increase in the fees for educational institutions to participate in the relevant scheme.</li><br>
					</ul>   
					<div class="contentTitle"><b>Trade Marks</b></div>
					<p>Except where otherwise specified, any word or device to which the TM or ® symbol is attached, is a trademark in which we claim proprietary rights. We also assert all our trademark rights under the common law or otherwise. If you use any of our trademarks in reference to our activities, products or services, you must include a statement attributing that trademark to us. You must not use any of our trademarks:</p>

					<ul>
						<li>in or as the whole or part of your own trade marks;</li><br>
						<li>in connection with activities, products or services which are not ours;</li><br>
						<li>in a manner which may be confusing, misleading ordeceptive;</li><br>
						<li>in a manner that disparages us or our information, products or services (including this Site).</li></br>
					</ul>
					<div class="contentTitle"><b>Termination</b></div>
					<p>We may terminate access to this Site at any time without notice. The Terms and Conditionswill nevertheless survive any such termination.</p>
					<p><strong>Links to other websites</strong></p>
					<ul>
						<li>The Site may contain links to third party sites (Linked Sites). Linked Sites are not under our control and we are not responsible for the content of any. We provide these hyperlinks to you as convenience only, and the inclusion of any link does not imply any endorsement of the Linked Site by us or by our directors, officers, agents, employees and contractors. You link to any Linked Site or subsequent site entirely at your own risk.</li><br>
						<li>Neither we nor our directors, officers, agents, employees and contractors give any representation or warranty as to the reliability, accuracy or completeness of any Linked Sites or subsequent sites, nor do they or we accept any responsibility arising in any way for errors in, or omissions from any Linked Sites or subsequent sites.</li><br>
					</ul>
					<div class="contentTitle"><b>General</b></div>
					<ul>
						<li>We do not accept any liability for any failure to comply with the Terms and Conditionswhere the failure is due to circumstances beyond our reasonable control.</li><br>
						<li>Our failure to act in a particular circumstance does not waive our ability to act with respect to that circumstances or similar circumstances.</li><br>
						<li>However, if we expressly waive any rights available to us under these Terms and Conditionson one occasion, this does not mean that those rights will automatically be waived on any other occasion.</li>
						<li>If any of the Terms and Conditionsare held to be invalid, unenforceable or illegal for any reason, the remaining terms and conditions will nevertheless continue in full force.</li><br>
					</ul>
					<div class="contentTitle"><b>Challenges and competitions</b></div>
					<p>From time to time, we host or operate challenges and competitions within the Site, which may be supported by third party sponsors. Challenges are designed to encourage school and student participation in a fun and engaging online learning event. These Terms and Conditions, including the Futuristic Privacy Policy, govern challenges and competitions, in addition to any other terms and conditions in place specifically for the relevant challenge or competition.</p>
					<ul>
						<li>Participants who do not comply with these Terms and Conditions, may be removed from the List of High Achieving Students or disqualified from the competition at any time, and we will use our complete discretion as to whether or not removal or disqualification occurs.</li><br>
						<li>Students, classes and schools may be required by us to provide proof of age and to sign a declaration that they individually and collectively participated without assistance from any other person, software, hardware or device.</li></br>
						<li>Any students, classes or schools intentionally misusing the Site be disqualified or removed from the List of High Achieving Students of the competition or challenge at any time. Examples of misuse include but are not limited to computer hacking of the Site, posting fraudulent results, using computer scripts to improve responses, scores or otherwise.</li><br>
						<li>We may, at our complete discretion, remove from competition any students, classes and schools not participating in courses or on content appropriate for their age. Prizes advertised for a challenge or competition may be substituted, for something of equivalent value, as determined by us or the prize provider at our complete discretion.</li><br>
					</ul>
					<div class="contentTitle"><b>Governing Law</b></div>
					<p>The laws in force in Western Australia, Australia, govern these Terms and Conditions. You agree to submit to the exclusive jurisdiction of the courts in Western Australia, Australia. However, we retain the right to bring legal proceedings in any jurisdiction where we believe that infringement of these Terms and Conditionsis taking place or originating.</p>
				</div>
			</div>
		</div>
	</div>
</section>
@endsection